
==== add the prometheus helm repo

[source,bash]
----
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts 
helm repo add stable https://charts.helm.sh/stable

----

update the repos

[source,bash]
----
helm repo update
----


kubectl create namespace prometheus

helm install prometheus prometheus-community/kube-prometheus-stack -n prometheus


port forward

kubectl port-forward deployment/prometheus-grafana 3000 -n prometheus

get the admin secret
kubectl get secret prometheus-grafana --namespace prometheus -o jsonpath="{.data.admin-password}" | base64 --decode ; echo 


create metrics viewer role in confluent cloud

confluent login
confluent iam service-account create prommetrics --description "prometheus monitoring"

should result in something like this

+-------------+-----------------------+
| ID          | sa-xxxxxx             |
| Name        | prommetrics           |
| Description | prometheus monitoring |
+-------------+-----------------------+

=== add role binding
confluent iam rbac role-binding create --role MetricsViewer --principal User:sa-35d9jo

confluent iam rbac role-binding list --principal User:sa-35d9jo

confluent iam service-account list | grep sa-35d9jo


# create an api key for the new service account
confluent api-key create --resource cloud --service-account sa-35d9jo

should result in something like 
+------------+------------------------------------------------------------------+
| API Key    | EIXNNADZZWLJUMQQ                                                 |
| API Secret | bJmXgfRTNHi51nVKwbCTk5u/W41sZYZGAR7T0rkzVVS6sCoQKBFjj2J2adWV99JB |
+------------+------------------------------------------------------------------+

note down API key and api secret for later usage



create confluent cloud scrape conf

use API Key and Secret from above

- job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: API Key
      password: API Secret
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-1234
        - lkc-2345
	"resource.connector.id":
        - lcc-1234
        - lcc-2345
    "resource.schema_registry.id":
      - lsrc-1234